
export const GET_DATA='GET_DATA'
export const ERROR_DATA='ERROR_DATA'
export const LOAD_DATA='LOAD_DATA'

export const MODIFY_ITEM_SIZE = "MODIFY_ITEM_SIZE";
export const MODIFY_ITEM_QUANTITY = "MODIFY_ITEM_QUANTITY";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const MAKE_CART_EMPTY = "MAKE_CART_EMPTY";

export const REMOVE_WISHLIST_ITEM = "REMOVE_WISHLIST_ITEM";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";

export const UPDATE_ADDRESS = "UPDATE_ADDRESS";


export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";


