const GET_DATA='GET_DATA'
const ERROR_DATA='ERROR_DATA'
const LOAD_DATA = 'LOAD_DATA'

export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";




export{GET_DATA,ERROR_DATA,LOAD_DATA}