export const designers = [
     { label: "A Bathing Ape", value: "A Bathing Ape" },
     { label: "A.L.C.", value: "A.L.C." },
     { label: "A.P.C.", value: "A.P.C." },
     { label: "A_COLD_WALL*", value: "A_COLD_WALL*" },
     { label: "Acne Studios", value: "Acne Studios" },
     { label: "Add", value: "Add" },
     { label: "ADER error", value: "ADER error" },
     { label: "adidas", value: "adidas" },
     { label: "adidas Originals", value: "adidas Originals" },
     { label: "Adornia", value: "Adornia" },
     { label: "Aeron", value: "Aeron" },
     { label: "Aeyde", value: "Aeyde" },
     { label: "AG Jeans", value: "AG Jeans" },
     { label: "Agent Provocateur", value: "Agent Provocateur" },
     { label: "Aglini", value: "Aglini" },
     { label: "Agnona", value: "Agnona" },
     { label: "Agolde", value: "Agolde" },
     { label: "Agua by Agua Bendita", value: "Agua by Agua Bendita" },
     { label: "Alaïa", value: "Alaïa" },
     { label: "Alanui", value: "Alanui" },
     { label: "Alberta Ferretti", value: "Alberta Ferretti" },
     { label: "Alessandra Rich", value: "Alessandra Rich" },
     { label: "Alessandro Dell'acqua", value: "Alessandro Dell'acqua" },
     { label: "ALESSIA SANTI", value: "ALESSIA SANTI" },
     { label: "Alex Mill", value: "Alex Mill" },
     { label: "Alex Perry", value: "Alex Perry" },
     { label: "Alexander McQueen", value: "Alexander McQueen" },
     { label: "Alexander Wang", value: "Alexander Wang" },
     { label: "Alexandre Birman", value: "Alexandre Birman" },
     { label: "Alexandre Vauthier", value: "Alexandre Vauthier" },
     { label: "Alexia Admor", value: "Alexia Admor" },
     { label: "Alexis", value: "Alexis" },
     { label: "Alice + Olivia", value: "Alice + Olivia" },
     { label: "Alighieri", value: "Alighieri" },
     { label: "Alix", value: "Alix" },
     { label: "AllSaints", value: "AllSaints" },
     { label: "Allude", value: "Allude" },
     { label: "Alo Yoga", value: "Alo Yoga" },
     { label: "Alpha Industries", value: "Alpha Industries" },
     { label: "Alpha Studio", value: "Alpha Studio" },
     { label: "Altea", value: "Altea" },
     { label: "Altuzarra", value: "Altuzarra" },
     { label: "Alysi", value: "Alysi" },
     { label: "Amanda Uprichard", value: "Amanda Uprichard" },
     { label: "Ambush", value: "Ambush" },
     { label: "Amen", value: "Amen" },
     { label: "American Vintage", value: "American Vintage" },
     { label: "AMI", value: "AMI" },
     { label: "AMINA MUADDI", value: "AMINA MUADDI" },
     { label: "Amir Slama", value: "Amir Slama" },
     { label: "Amiri", value: "Amiri" },
     { label: "Ancient Greek Sandals", value: "Ancient Greek Sandals" },
     { label: "and wander", value: "and wander" },
     { label: "ANDERSSON BELL", value: "ANDERSSON BELL" },
     { label: "Angelo Nardelli", value: "Angelo Nardelli" },
     { label: "Anine Bing", value: "Anine Bing" },
     { label: "Anita Ko", value: "Anita Ko" },
     { label: "Aniye By", value: "Aniye By" },
     { label: "Ann Demeulemeester", value: "Ann Demeulemeester" },
     { label: "Ann Taylor", value: "Ann Taylor" },
     { label: "Anne Klein", value: "Anne Klein" },
     { label: "Annoushka", value: "Annoushka" },
     { label: "Anonyme Designers", value: "Anonyme Designers" },
     { label: "Antonelli", value: "Antonelli" },
     { label: "Apparis", value: "Apparis" },
     { label: "Aquazzura", value: "Aquazzura" },
     { label: "Area", value: "Area" },
     { label: "Aries", value: "Aries" },
     { label: "ARIZONA LOVE", value: "ARIZONA LOVE" },
     { label: "Armani Exchange", value: "Armani Exchange" },
     { label: "Armani Jeans", value: "Armani Jeans" },
     { label: "Artisan", value: "Artisan" },
     { label: "Asceno", value: "Asceno" },
     { label: "Ash", value: "Ash" },
     { label: "Asics", value: "Asics" },
     { label: "Aspesi", value: "Aspesi" },
     { label: "Aspinal of London", value: "Aspinal of London" },
     { label: "Astley Clarke", value: "Astley Clarke" },
     { label: "AT.P.CO", value: "AT.P.CO" },
     { label: "ATM", value: "ATM" },
     { label: "Atp Atelier", value: "Atp Atelier" },
     { label: "Attic And Barn", value: "Attic And Barn" },
     { label: "August Steiner", value: "August Steiner" },
     { label: "AURALEE", value: "AURALEE" },
     { label: "Auree", value: "Auree" },
     { label: "Aurelie Bidermann", value: "Aurelie Bidermann" },
     { label: "Automobili Lamborghin", value: "Automobili Lamborghin" },
     { label: "Autry", value: "Autry" },
     { label: "Autumn Cashmere", value: "Autumn Cashmere" },
     { label: "AWAKE NY", value: "AWAKE NY" },
     { label: "Axel Arigato", value: "Axel Arigato" },
     { label: "AZ FACTORY", value: "AZ FACTORY" },
     { label: "B", value: "B" },
     { label: "B+ AB", value: "B+ AB" },
     { label: "B.D. Baggies", value: "B.D. Baggies" },
     { label: "Ba&sh", value: "Ba&sh" },
     { label: "Badgley Mischka", value: "Badgley Mischka" },
     { label: "Bagutta", value: "Bagutta" },
     { label: "Baldinini", value: "Baldinini" },
     { label: "Balenciaga", value: "Balenciaga" },
     { label: "Ballantyne", value: "Ballantyne" },
     { label: "Bally", value: "Bally" },
     { label: "Balmain", value: "Balmain" },
     { label: "Bao Bao Issey Miyake", value: "Bao Bao Issey Miyake" },
     { label: "Baracuta", value: "Baracuta" },
     { label: "Barba", value: "Barba" },
     { label: "Barba Napoli", value: "Barba Napoli" },
     { label: "Barbour", value: "Barbour" },
     { label: "Barena", value: "Barena" },
     { label: "Barrie", value: "Barrie" },
     { label: "Barrow", value: "Barrow" },
     { label: "Baserange", value: "Baserange" },
     { label: "Baum und Pferdgarten", value: "Baum und Pferdgarten" },
     { label: "BBCICECREAM", value: "BBCICECREAM" },
     { label: "BCBGeneration", value: "BCBGeneration" },
     { label: "BCBGMAXAZRIA", value: "BCBGMAXAZRIA" },
     { label: "be Blumarine", value: "be Blumarine" },
     { label: "Beams Plus", value: "Beams Plus" },
     { label: "Beatrice B.", value: "Beatrice B." },
     { label: "Bebe", value: "Bebe" },
     { label: "Bellerose", value: "Bellerose" },
     { label: "Belpearl", value: "Belpearl" },
     { label: "Belstaff", value: "Belstaff" },
     { label: "Ben Sherman", value: "Ben Sherman" },
     { label: "Berna", value: "Berna" },
     { label: "Berwich", value: "Berwich" },
     { label: "Bikkembergs", value: "Bikkembergs" },
     { label: "Billionaire", value: "Billionaire" },
     { label: "Birkenstock", value: "Birkenstock" },
     { label: "Black Halo", value: "Black Halo" },
     { label: "Blauer", value: "Blauer" },
     { label: "Blue & Cream", value: "Blue & Cream" },
     { label: "Blugirl Blumarine", value: "Blugirl Blumarine" },
     { label: "Blumarine", value: "Blumarine" },
     { label: "Bobbies", value: "Bobbies" },
     { label: "Bode", value: "Bode" },
     { label: "Boglioli", value: "Boglioli" },
     { label: "Bogner", value: "Bogner" },
     { label: "Bondi Born", value: "Bondi Born" },
     { label: "Borsalino", value: "Borsalino" },
     { label: "BOSS by HUGO BOSS", value: "BOSS by HUGO BOSS" },
     { label: "Bottega Veneta", value: "Bottega Veneta" },
     { label: "Boucheron", value: "Boucheron" },
     { label: "Boutique Moschino", value: "Boutique Moschino" },
     { label: "Boyy", value: "Boyy" },
     { label: "Brain Dead", value: "Brain Dead" },
     { label: "Brian Dales", value: "Brian Dales" },
     { label: "Briglia 1949", value: "Briglia 1949" },
     { label: "Brioni", value: "Brioni" },
     { label: "Brooks Brothers", value: "Brooks Brothers" },
     { label: "Brooksfield", value: "Brooksfield" },
     { label: "Brunello Cucinelli", value: "Brunello Cucinelli" },
     { label: "Burberry", value: "Burberry" },
     { label: "Butter Goods", value: "Butter Goods" },
     { label: "BVLGARI", value: "BVLGARI" },
     { label: "BY FAR", value: "BY FAR" },
     { label: "By Malene Birger", value: "By Malene Birger" },
     { label: "C", value: "C" },
     { label: "C.P. Company", value: "C.P. Company" },
     { label: "CafeNoir", value: "CafeNoir" },
     { label: "Caliban", value: "Caliban" },
     { label: "Calvin Klein", value: "Calvin Klein" },
     { label: "Camicettasnob", value: "Camicettasnob" },
     { label: "Camila Coelho", value: "Camila Coelho" },
     { label: "Camilla", value: "Camilla" },
     { label: "Camper", value: "Camper" },
     { label: "CAMPERLAB", value: "CAMPERLAB" },
     { label: "Campomaggi", value: "Campomaggi" },
     { label: "Canada Goose", value: "Canada Goose" },
     { label: "Canali", value: "Canali" },
     { label: "Caractere", value: "Caractere" },
     { label: "Care Label", value: "Care Label" },
     { label: "Carhartt", value: "Carhartt" },
     { label: "Carhartt WIP", value: "Carhartt WIP" },
     { label: "Carolina Herrera", value: "Carolina Herrera" },
     { label: "Caroline Constas", value: "Caroline Constas" },
     { label: "Cartier", value: "Cartier" },
     { label: "Caruso", value: "Caruso" },
     { label: "Carvela Kurt Geiger", value: "Carvela Kurt Geiger" },
     { label: "CASABLANCA", value: "CASABLANCA" },
     { label: "Casadei", value: "Casadei" },
     { label: "Castañer", value: "Castañer" },
     { label: "CDLP", value: "CDLP" },
     { label: "Cecilie Bahnsen", value: "Cecilie Bahnsen" },
     { label: "Celine", value: "Celine" },
     { label: "Champion", value: "Champion" },
     { label: "Chantelle", value: "Chantelle" },
     { label: "Chaser", value: "Chaser" },
     { label: "Chiara Ferragni", value: "Chiara Ferragni" },
     { label: "Chinti & Parker", value: "Chinti & Parker" },
     { label: "Chloé", value: "Chloé" },
     { label: "Chocoolate", value: "Chocoolate" },
     { label: "Chopard", value: "Chopard" },
     { label: "Chopova Lowena", value: "Chopova Lowena" },
     { label: "Christian Louboutin", value: "Christian Louboutin" },
     { label: "Christopher Esber", value: "Christopher Esber" },
     { label: "Christopher Kane", value: "Christopher Kane" },
     { label: "Church's", value: "Church's" },
     { label: "Ciesse Piumini", value: "Ciesse Piumini" },
     { label: "Cinq À Sept", value: "Cinq À Sept" },
     { label: "Circolo 1901", value: "Circolo 1901" },
     { label: "Citizens of Humanity", value: "Citizens of Humanity" },
     { label: "Clarks", value: "Clarks" },
     { label: "Class Roberto Cavalli", value: "Class Roberto Cavalli" },
     { label: "Claudie Pierlot", value: "Claudie Pierlot" },
     { label: "Clips", value: "Clips" },
     { label: "Closed", value: "Closed" },
     { label: "Closet", value: "Closet" },
     { label: "Clube Bossa", value: "Clube Bossa" },
     { label: "Co.", value: "Co." },
     { label: "COACH", value: "COACH" },
     { label: "Coccinelle", value: "Coccinelle" },
     { label: "Collina Strada", value: "Collina Strada" },
     { label: "Colmar", value: "Colmar" },
     { label: "COLORFUL STANDARD", value: "COLORFUL STANDARD" },
     { label: "Columbia", value: "Columbia" },
     { label: "Commando", value: "Commando" },
     { label: "Comme des Garçons", value: "Comme des Garçons" },
     { label: "COMME DES GARÇONS PLA", value: "COMME DES GARÇONS PLA" },
     { label: "Common Projects", value: "Common Projects" },
     { label: "Conquista", value: "Conquista" },
     { label: "Converse", value: "Converse" },
     { label: "Coperni", value: "Coperni" },
     { label: "Corneliani", value: "Corneliani" },
     { label: "Cosabella", value: "Cosabella" },
     { label: "Costumein", value: "Costumein" },
     { label: "Cotton Citizen", value: "Cotton Citizen" },
     { label: "Courreges", value: "Courreges" },
     { label: "Craig Green", value: "Craig Green" },
     { label: "Crocs™", value: "Crocs™" },
     { label: "Cruciani", value: "Cruciani" },
     { label: "Cruna", value: "Cruna" },
     { label: "Cult Gaia", value: "Cult Gaia" },
     { label: "Cutler and Gross", value: "Cutler and Gross" },
     { label: "CYCLE", value: "CYCLE" },
     { label: "D", value: "D" },
     { label: "D.exterior", value: "D.exterior" },
     { label: "Daily Paper", value: "Daily Paper" },
     { label: "Daniel", value: "Daniel" },
     { label: "Daniele Alessandrini", value: "Daniele Alessandrini" },
     { label: "Daniele Fiesoli", value: "Daniele Fiesoli" },
     { label: "David Yurman", value: "David Yurman" },
     { label: "Department 5", value: "Department 5" },
     { label: "Derek Rose", value: "Derek Rose" },
     { label: "Desigual", value: "Desigual" },
     { label: "Deus Ex Machina", value: "Deus Ex Machina" },
     { label: "Diadora", value: "Diadora" },
     { label: "Diana M. Jewels", value: "Diana M. Jewels" },
     { label: "Diane von Furstenberg", value: "Diane von Furstenberg" },
     { label: "Dickies", value: "Dickies" },
     { label: "DIESEL", value: "DIESEL" },
     { label: "Dime", value: "Dime" },
     { label: "Dion Lee", value: "Dion Lee" },
     { label: "Dior", value: "Dior" },
     { label: "DISCLAIMER", value: "DISCLAIMER" },
     { label: "Dita Eyewear", value: "Dita Eyewear" },
     { label: "Divine Follie", value: "Divine Follie" },
     { label: "Dixie", value: "Dixie" },
     { label: "DKNY", value: "DKNY" },
     { label: "Dodo Bar Or", value: "Dodo Bar Or" },
     { label: "Dolce & Gabbana", value: "Dolce & Gabbana" },
     { label: "Domenico Tagliente", value: "Domenico Tagliente" },
     { label: "Dondup", value: "Dondup" },
     { label: "Dorothee Schumacher", value: "Dorothee Schumacher" },
     { label: "Doucal's", value: "Doucal's" },
     { label: "Dr. Martens", value: "Dr. Martens" },
     { label: "Dries Van Noten", value: "Dries Van Noten" },
     { label: "Drole de Monsieur", value: "Drole de Monsieur" },
     { label: "DROMe", value: "DROMe" },
     { label: "Drumohr", value: "Drumohr" },
     { label: "DSquared²", value: "DSquared²" },
     { label: "Dune", value: "Dune" },
     { label: "Dunhill", value: "Dunhill" },
     { label: "E", value: "E" },
     { label: "EA7", value: "EA7" },
     { label: "Eastpak", value: "Eastpak" },
     { label: "EBARRITO", value: "EBARRITO" },
     { label: "Eberjey", value: "Eberjey" },
     { label: "Eckhaus Latta", value: "Eckhaus Latta" },
     { label: "Edwin", value: "Edwin" },
     { label: "Eera", value: "Eera" },
     { label: "Effy", value: "Effy" },
     { label: "ELEVEN PARIS", value: "ELEVEN PARIS" },
     { label: "Eleventy", value: "Eleventy" },
     { label: "Elie Tahari", value: "Elie Tahari" },
     { label: "Elisabetta Franchi", value: "Elisabetta Franchi" },
     { label: "Emanuele Bicocchi", value: "Emanuele Bicocchi" },
     { label: "Ember Fine Jewelry", value: "Ember Fine Jewelry" },
     { label: "Emilio Pucci", value: "Emilio Pucci" },
     { label: "EMMA & GAIA", value: "EMMA & GAIA" },
     { label: "Emporio Armani", value: "Emporio Armani" },
     { label: "Engineered Garments", value: "Engineered Garments" },
     { label: "Entre Amis", value: "Entre Amis" },
     { label: "Enza Costa", value: "Enza Costa" },
     { label: "Equipment", value: "Equipment" },
     { label: "Erdem", value: "Erdem" },
     { label: "Eres", value: "Eres" },
     { label: "Erika Cavallini Semi ", value: "Erika Cavallini Semi " },
     { label: "ERL", value: "ERL" },
     { label: "Ermanno Scervino", value: "Ermanno Scervino" },
     { label: "Ermenegildo Zegna", value: "Ermenegildo Zegna" },
     { label: "Eskandar", value: "Eskandar" },
     { label: "Essentiel Antwerp", value: "Essentiel Antwerp" },
     { label: "Étoile Isabel Marant", value: "Étoile Isabel Marant" },
     { label: "Etro", value: "Etro" },
     { label: "Etudes Studio", value: "Etudes Studio" },
     { label: "European Culture", value: "European Culture" },
     { label: "Exte", value: "Exte" },
     { label: "Extreme Cashmere", value: "Extreme Cashmere" },
     { label: "Eye Candy LA", value: "Eye Candy LA" },
     { label: "Eytys", value: "Eytys" },
     { label: "F", value: "F" },
     { label: "Fabi", value: "Fabi" },
     { label: "Fabiana Filippi", value: "Fabiana Filippi" },
     { label: "FABIENNE CHAPOT", value: "FABIENNE CHAPOT" },
     { label: "Faherty", value: "Faherty" },
     { label: "Faithfull The Brand", value: "Faithfull The Brand" },
     { label: "Faliero Sarti", value: "Faliero Sarti" },
     { label: "FALKE", value: "FALKE" },
     { label: "FAMILY FIRST Milano", value: "FAMILY FIRST Milano" },
     { label: "Farah", value: "Farah" },
     { label: "Fay", value: "Fay" },
     { label: "Fear Of God", value: "Fear Of God" },
     { label: "Fear of God ESSENTIAL", value: "Fear of God ESSENTIAL" },
     { label: "Fedeli", value: "Fedeli" },
     { label: "FEDERICA TOSI", value: "FEDERICA TOSI" },
     { label: "Fendi", value: "Fendi" },
     { label: "Feng Chen Wang", value: "Feng Chen Wang" },
     { label: "Ferragamo", value: "Ferragamo" },
     { label: "Ferrari", value: "Ferrari" },
     { label: "Fila", value: "Fila" },
     { label: "Filippa K", value: "Filippa K" },
     { label: "Fiorio", value: "Fiorio" },
     { label: "Fiorucci", value: "Fiorucci" },
     { label: "Fisico", value: "Fisico" },
     { label: "Fjallraven", value: "Fjallraven" },
     { label: "Fleur du Mal", value: "Fleur du Mal" },
     { label: "Folk", value: "Folk" },
     { label: "For Love & Lemons", value: "For Love & Lemons" },
     { label: "Forte", value: "Forte" },
     { label: "Forte Forte", value: "Forte Forte" },
     { label: "FRAME", value: "FRAME" },
     { label: "Frankie Morello", value: "Frankie Morello" },
     { label: "Fred Perry", value: "Fred Perry" },
     { label: "Free People", value: "Free People" },
     { label: "French Connection", value: "French Connection" },
     { label: "Frescobol Carioca", value: "Frescobol Carioca" },
     { label: "Fucking Awesome", value: "Fucking Awesome" },
     { label: "Furla", value: "Furla" },
     { label: "G", value: "G" },
     { label: "G-Star RAW", value: "G-Star RAW" },
     { label: "Gabi Rielle", value: "Gabi Rielle" },
     { label: "Gabor", value: "Gabor" },
     { label: "Gabriela Hearst", value: "Gabriela Hearst" },
     { label: "Gaelle Paris", value: "Gaelle Paris" },
     { label: "Galvan London", value: "Galvan London" },
     { label: "Ganni", value: "Ganni" },
     { label: "GANT", value: "GANT" },
     { label: "Garcia", value: "Garcia" },
     { label: "Garrett Leight", value: "Garrett Leight" },
     { label: "GAUDI", value: "GAUDI" },
     { label: "GAUGE81", value: "GAUGE81" },
     { label: "Gazzarrini", value: "Gazzarrini" },
     { label: "Gcds", value: "Gcds" },
     { label: "Gemondo", value: "Gemondo" },
     { label: "Genevive Jewelry", value: "Genevive Jewelry" },
     { label: "Gentry Portofino", value: "Gentry Portofino" },
     { label: "Geox", value: "Geox" },
     { label: "Gestuz", value: "Gestuz" },
     { label: "GHŌUD", value: "GHŌUD" },
     { label: "Gia Borghini", value: "Gia Borghini" },
     { label: "Giambattista Valli", value: "Giambattista Valli" },
     { label: "Gianvito Rossi", value: "Gianvito Rossi" },
     { label: "Giorgio Armani", value: "Giorgio Armani" },
     { label: "GIRLFRIEND COLLECTIVE", value: "GIRLFRIEND COLLECTIVE" },
     { label: "GIUSEPPE DI MORABITO", value: "GIUSEPPE DI MORABITO" },
     { label: "Giuseppe Zanotti", value: "Giuseppe Zanotti" },
     { label: "Givenchy", value: "Givenchy" },
     { label: "Glaze Jewelry", value: "Glaze Jewelry" },
     { label: "Goldbergh", value: "Goldbergh" },
     { label: "Golden Goose", value: "Golden Goose" },
     { label: "GOOD AMERICAN", value: "GOOD AMERICAN" },
     { label: "Gracia", value: "Gracia" },
     { label: "Gramicci", value: "Gramicci" },
     { label: "Gran Sasso", value: "Gran Sasso" },
     { label: "Grey Daniele Alessand", value: "Grey Daniele Alessand" },
     { label: "Gucci", value: "Gucci" },
     { label: "Guess", value: "Guess" },
     { label: "Guidi", value: "Guidi" },
     { label: "Gv2", value: "Gv2" },
     { label: "H&M", value: "H&M" },
     { label: "Hackett", value: "Hackett" },
     { label: "Haikure", value: "Haikure" },
     { label: "Hale Bob", value: "Hale Bob" },
     { label: "Halston", value: "Halston" },
     { label: "Hannah Rose", value: "Hannah Rose" },
     { label: "Hanro", value: "Hanro" },
     { label: "Harmont & Blaine", value: "Harmont & Blaine" },
     { label: "Harris Wharf London", value: "Harris Wharf London" },
     { label: "Hartford", value: "Hartford" },
     { label: "Hatton Labs", value: "Hatton Labs" },
     { label: "Havaianas", value: "Havaianas" },
     { label: "Haveone", value: "Haveone" },
     { label: "Helmut Lang", value: "Helmut Lang" },
     { label: "Henrik Vibskov", value: "Henrik Vibskov" },
     { label: "Heritage", value: "Heritage" },
     { label: "Herno", value: "Herno" },
     { label: "Heron Preston", value: "Heron Preston" },
     { label: "Herschel Supply Co.", value: "Herschel Supply Co." },
     { label: "Hervé Léger", value: "Hervé Léger" },
     { label: "HIDE & JACK", value: "HIDE & JACK" },
     { label: "Hobbs", value: "Hobbs" },
     { label: "Hogan", value: "Hogan" },
     { label: "Holzweiler", value: "Holzweiler" },
     { label: "Howlin'", value: "Howlin'" },
     { label: "Hudson Jeans", value: "Hudson Jeans" },
     { label: "Huf", value: "Huf" },
     { label: "HUGO", value: "HUGO" },
     { label: "HUNTER", value: "HUNTER" },
     { label: "Hunza G", value: "Hunza G" },
     { label: "Hush Puppies", value: "Hush Puppies" },
     { label: "Hydrogen", value: "Hydrogen" },
     { label: "I", value: "I" },
     { label: "I. REISS", value: "I. REISS" },
     { label: "Iceberg", value: "Iceberg" },
     { label: "ih nom uh nit", value: "ih nom uh nit" },
     { label: "Imperial", value: "Imperial" },
     { label: "Incotex", value: "Incotex" },
     { label: "Invicta", value: "Invicta" },
     { label: "IRO", value: "IRO" },
     { label: "Isa Boulder", value: "Isa Boulder" },
     { label: "Isabel Marant", value: "Isabel Marant" },
     { label: "Izzue", value: "Izzue" },
     { label: "J", value: "J" },
     { label: "J Brand", value: "J Brand" },
     { label: "J.Lindeberg", value: "J.Lindeberg" },
     { label: "J.McLaughlin", value: "J.McLaughlin" },
     { label: "Jack & Jones", value: "Jack & Jones" },
     { label: "Jacob Cohen", value: "Jacob Cohen" },
     { label: "Jacquemus", value: "Jacquemus" },
     { label: "JADE Swim", value: "JADE Swim" },
     { label: "James Perse", value: "James Perse" },
     { label: "Jane Basch", value: "Jane Basch" },
     { label: "Jean Paul Gaultier", value: "Jean Paul Gaultier" },
     { label: "Jeckerson", value: "Jeckerson" },
     { label: "Jeffrey Campbell", value: "Jeffrey Campbell" },
     { label: "Jejia", value: "Jejia" },
     { label: "Jennifer Behr", value: "Jennifer Behr" },
     { label: "Jijil", value: "Jijil" },
     { label: "Jil Sander", value: "Jil Sander" },
     { label: "Jimmy Choo", value: "Jimmy Choo" },
     { label: "Joe's Jeans", value: "Joe's Jeans" },
     { label: "Johanna Ortiz", value: "Johanna Ortiz" },
     { label: "John Elliott", value: "John Elliott" },
     { label: "John Galliano", value: "John Galliano" },
     { label: "John Hardy", value: "John Hardy" },
     { label: "John Richmond", value: "John Richmond" },
     { label: "John Smedley", value: "John Smedley" },
     { label: "John Varvatos", value: "John Varvatos" },
     { label: "Johnny Was", value: "Johnny Was" },
     { label: "Joie", value: "Joie" },
     { label: "Jonathan Simkhai", value: "Jonathan Simkhai" },
     { label: "JOSEPH", value: "JOSEPH" },
     { label: "Joseph Ribkoff", value: "Joseph Ribkoff" },
     { label: "Jucca", value: "Jucca" },
     { label: "Juicy Couture", value: "Juicy Couture" },
     { label: "Junya Watanabe", value: "Junya Watanabe" },
     { label: "Just Cavalli", value: "Just Cavalli" },
     { label: "Juun.J", value: "Juun.J" },
     { label: "JW Anderson", value: "JW Anderson" },
     { label: "K", value: "K" },
     { label: "K-Way", value: "K-Way" },
     { label: "Kaos", value: "Kaos" },
     { label: "Kapital", value: "Kapital" },
     { label: "Kappa", value: "Kappa" },
     { label: "Karl Lagerfeld", value: "Karl Lagerfeld" },
     { label: "Kate Spade", value: "Kate Spade" },
     { label: "Kenneth Jay Lane", value: "Kenneth Jay Lane" },
     { label: "KENZO", value: "KENZO" },
     { label: "KG by Kurt Geiger", value: "KG by Kurt Geiger" },
     { label: "Khaite", value: "Khaite" },
     { label: "Khrisjoy", value: "Khrisjoy" },
     { label: "Kiki de Montparnasse", value: "Kiki de Montparnasse" },
     { label: "Kiton", value: "Kiton" },
     { label: "KNWLS", value: "KNWLS" },
     { label: "Kocca", value: "Kocca" },
     { label: "Koche", value: "Koche" },
     { label: "Ksubi", value: "Ksubi" },
     { label: "KTZ", value: "KTZ" },
     { label: "Kuboraum", value: "Kuboraum" },
     { label: "Kurt Geiger", value: "Kurt Geiger" },
     { label: "L", value: "L" },
     { label: "L'academie", value: "L'academie" },
     { label: "L'Agence", value: "L'Agence" },
     { label: "L'Autre Chose", value: "L'Autre Chose" },
     { label: "L*Space", value: "L*Space" },
     { label: "La DoubleJ", value: "La DoubleJ" },
     { label: "La Martina", value: "La Martina" },
     { label: "La Perla", value: "La Perla" },
     { label: "Lacoste", value: "Lacoste" },
     { label: "Lafayette 148 New Yor", value: "Lafayette 148 New Yor" },
     { label: "Laines London", value: "Laines London" },
     { label: "Laneus", value: "Laneus" },
     { label: "Lanvin", value: "Lanvin" },
     { label: "Lardini", value: "Lardini" },
     { label: "LÁTELITA London", value: "LÁTELITA London" },
     { label: "Lauren by Ralph Laure", value: "Lauren by Ralph Laure" },
     { label: "Le Gramme", value: "Le Gramme" },
     { label: "Le Sarte Pettegole", value: "Le Sarte Pettegole" },
     { label: "Le Silla", value: "Le Silla" },
     { label: "Le Vian", value: "Le Vian" },
     { label: "Lee Jeans", value: "Lee Jeans" },
     { label: "Lemaire", value: "Lemaire" },
     { label: "Les Copains", value: "Les Copains" },
     { label: "Les Hommes", value: "Les Hommes" },
     { label: "Les Tien", value: "Les Tien" },
     { label: "Levi's", value: "Levi's" },
     { label: "Liberty", value: "Liberty" },
     { label: "Linda Farrow", value: "Linda Farrow" },
     { label: "Lisa Marie Fernandez", value: "Lisa Marie Fernandez" },
     { label: "Lisa Yang", value: "Lisa Yang" },
     { label: "Liu Jo", value: "Liu Jo" },
     { label: "Live The Process", value: "Live The Process" },
     { label: "Liviana Conti", value: "Liviana Conti" },
     { label: "Loeffler Randall", value: "Loeffler Randall" },
     { label: "Loewe", value: "Loewe" },
     { label: "Longchamp", value: "Longchamp" },
     { label: "Lorena Antoniazzi", value: "Lorena Antoniazzi" },
     { label: "Loro Piana", value: "Loro Piana" },
     { label: "Lotus", value: "Lotus" },
     { label: "Louisa Ballou", value: "Louisa Ballou" },
     { label: "Loulou Studio", value: "Loulou Studio" },
     { label: "Love Moschino", value: "Love Moschino" },
     { label: "Love Stories", value: "Love Stories" },
     { label: "Lovers + Friends", value: "Lovers + Friends" },
     { label: "LoveShackFancy", value: "LoveShackFancy" },
     { label: "Low Brand", value: "Low Brand" },
     { label: "Low Classic", value: "Low Classic" },
     { label: "Lygia & Nanny", value: "Lygia & Nanny" },
     { label: "Lyle & Scott", value: "Lyle & Scott" },
     { label: "M", value: "M" },
     { label: "M Missoni", value: "M Missoni" },
     { label: "Mach & Mach", value: "Mach & Mach" },
     { label: "Mackage", value: "Mackage" },
     { label: "Mackintosh", value: "Mackintosh" },
     { label: "Magda Butrym", value: "Magda Butrym" },
     { label: "Maharishi", value: "Maharishi" },
     { label: "Maison Kitsuné", value: "Maison Kitsuné" },
     { label: "Maison Labiche", value: "Maison Labiche" },
     { label: "Maison Lejaby", value: "Maison Lejaby" },
     { label: "Maison Margiela", value: "Maison Margiela" },
     { label: "Maison Michel", value: "Maison Michel" },
     { label: "Maje", value: "Maje" },
     { label: "Majestic Filatures", value: "Majestic Filatures" },
     { label: "MAJORELLE", value: "MAJORELLE" },
     { label: "Maliparmi", value: "Maliparmi" },
     { label: "Malo", value: "Malo" },
     { label: "Malone Souliers", value: "Malone Souliers" },
     { label: "Manebí", value: "Manebí" },
     { label: "Mangano", value: "Mangano" },
     { label: "Manila Grace", value: "Manila Grace" },
     { label: "Manolo Blahnik", value: "Manolo Blahnik" },
     { label: "MANU Atelier", value: "MANU Atelier" },
     { label: "Manuel Ritz", value: "Manuel Ritz" },
     { label: "Marc Cain", value: "Marc Cain" },
     { label: "Marc Ellis", value: "Marc Ellis" },
     { label: "Marc Jacobs", value: "Marc Jacobs" },
     { label: "Marcelo Burlon", value: "Marcelo Burlon" },
     { label: "Marchesa notte", value: "Marchesa notte" },
     { label: "Marciano", value: "Marciano" },
     { label: "Marella", value: "Marella" },
     { label: "Maria Black", value: "Maria Black" },
     { label: "Maria Tash", value: "Maria Tash" },
     { label: "Marine Serre", value: "Marine Serre" },
     { label: "Market", value: "Market" },
     { label: "Marni", value: "Marni" },
     { label: "Marques'Almeida", value: "Marques'Almeida" },
     { label: "Marsèll", value: "Marsèll" },
     { label: "Martine Rose", value: "Martine Rose" },
     { label: "Marysia Swim", value: "Marysia Swim" },
     { label: "Mason's", value: "Mason's" },
     { label: "Massimo Alba", value: "Massimo Alba" },
     { label: "Mateo", value: "Mateo" },
     { label: "Mauro Grifoni", value: "Mauro Grifoni" },
     { label: "Max Mara", value: "Max Mara" },
     { label: "Max Mara Studio", value: "Max Mara Studio" },
     { label: "Max Studio", value: "Max Studio" },
     { label: "MAX&Co.", value: "MAX&Co." },
     { label: "Mc2 Saint Barth", value: "Mc2 Saint Barth" },
     { label: "MCM", value: "MCM" },
     { label: "McQ", value: "McQ" },
     { label: "MEIMEIJ", value: "MEIMEIJ" },
     { label: "Melissa", value: "Melissa" },
     { label: "Melissa Odabash", value: "Melissa Odabash" },
     { label: "Miaou", value: "Miaou" },
     { label: "Michael Coal", value: "Michael Coal" },
     { label: "Michael Costello", value: "Michael Costello" },
     { label: "Michael Kors", value: "Michael Kors" },
     { label: "MICHAEL Michael Kors", value: "MICHAEL Michael Kors" },
     { label: "Michael Stars", value: "Michael Stars" },
     { label: "MISBHV", value: "MISBHV" },
     { label: "Missoma", value: "Missoma" },
     { label: "Missoni", value: "Missoni" },
     { label: "Miu Miu", value: "Miu Miu" },
     { label: "Moma", value: "Moma" },
     { label: "Momoní", value: "Momoní" },
     { label: "Monary", value: "Monary" },
     { label: "Moncler", value: "Moncler" },
     { label: "Moncler Genius", value: "Moncler Genius" },
     { label: "Monica Vinader", value: "Monica Vinader" },
     { label: "Monrow", value: "Monrow" },
     { label: "Montblanc", value: "Montblanc" },
     { label: "Moon Boot", value: "Moon Boot" },
     { label: "Moorer", value: "Moorer" },
     { label: "Moose Knuckles", value: "Moose Knuckles" },
     { label: "Mos Mosh", value: "Mos Mosh" },
     { label: "Moschino", value: "Moschino" },
     { label: "Moschino Couture", value: "Moschino Couture" },
     { label: "Moss", value: "Moss" },
     { label: "Mother", value: "Mother" },
     { label: "Mou", value: "Mou" },
     { label: "MR P.", value: "MR P." },
     { label: "MSGM", value: "MSGM" },
     { label: "Mugler", value: "Mugler" },
     { label: "Mulberry", value: "Mulberry" },
     { label: "Munthe", value: "Munthe" },
     { label: "MW", value: "MW" },
     { label: "MY TWIN Twinset", value: "MY TWIN Twinset" },
     { label: "Mykita", value: "Mykita" },
     { label: "Myths", value: "Myths" },
     { label: "MZ Wallace", value: "MZ Wallace" },
     { label: "N", value: "N" },
     { label: "N.Peal Cashmere", value: "N.Peal Cashmere" },
     { label: "NA-KD", value: "NA-KD" },
     { label: "Nanette Lepore", value: "Nanette Lepore" },
     { label: "Nanushka", value: "Nanushka" },
     { label: "Napapijri", value: "Napapijri" },
     { label: "Natasha Zinko", value: "Natasha Zinko" },
     { label: "Natori", value: "Natori" },
     { label: "Nbd", value: "Nbd" },
     { label: "N°21", value: "N°21" },
     { label: "Needles", value: "Needles" },
     { label: "Neighborhood", value: "Neighborhood" },
     { label: "Neil Barrett", value: "Neil Barrett" },
     { label: "Nensi Dojaka", value: "Nensi Dojaka" },
     { label: "Nephora", value: "Nephora" },
     { label: "New Balance", value: "New Balance" },
     { label: "Nicholas", value: "Nicholas" },
     { label: "Nike", value: "Nike" },
     { label: "Nili Lotan", value: "Nili Lotan" },
     { label: "Nina Ricci", value: "Nina Ricci" },
     { label: "Nine West", value: "Nine West" },
     { label: "Nine:inthe:morning", value: "Nine:inthe:morning" },
     { label: "NINETY PERCENT", value: "NINETY PERCENT" },
     { label: "Niu", value: "Niu" },
     { label: "NN07", value: "NN07" },
     { label: "NO KA 'OI", value: "NO KA 'OI" },
     { label: "Norma Kamali", value: "Norma Kamali" },
     { label: "Norse Projects", value: "Norse Projects" },
     { label: "North Sails", value: "North Sails" },
     { label: "Nudie Jeans", value: "Nudie Jeans" },
     { label: "NYDJ", value: "NYDJ" },
     { label: "O", value: "O" },
     { label: "Oakley", value: "Oakley" },
     { label: "OAMC", value: "OAMC" },
     { label: "Obey", value: "Obey" },
     { label: "Odi Et Amo", value: "Odi Et Amo" },
     { label: "Off-White c/o Virgil ", value: "Off-White c/o Virgil " },
     { label: "Officina 36", value: "Officina 36" },
     { label: "Officine Creative", value: "Officine Creative" },
     { label: "Officine Generale", value: "Officine Generale" },
     { label: "Oliver Peoples", value: "Oliver Peoples" },
     { label: "Oliver Spencer", value: "Oliver Spencer" },
     { label: "Olympiah", value: "Olympiah" },
     { label: "On", value: "On" },
     { label: "On Running", value: "On Running" },
     { label: "One Teaspoon", value: "One Teaspoon" },
     { label: "Onia", value: "Onia" },
     { label: "ONLY", value: "ONLY" },
     { label: "Only & Sons", value: "Only & Sons" },
     { label: "Opening Ceremony", value: "Opening Ceremony" },
     { label: "Orciani", value: "Orciani" },
     { label: "Orlebar Brown", value: "Orlebar Brown" },
     { label: "Oscar de la Renta", value: "Oscar de la Renta" },
     { label: "Oséree", value: "Oséree" },
     { label: "Osklen", value: "Osklen" },
     { label: "Ottod'Ame", value: "Ottod'Ame" },
     { label: "OTTOLINGER", value: "OTTOLINGER" },
     { label: "Our Legacy", value: "Our Legacy" },
     { label: "P", value: "P" },
     { label: "P.A.R.O.S.H.", value: "P.A.R.O.S.H." },
     { label: "P.E Nation", value: "P.E Nation" },
     { label: "Paco Rabanne", value: "Paco Rabanne" },
     { label: "PAIGE", value: "PAIGE" },
     { label: "Paisie", value: "Paisie" },
     { label: "Pal Zileri", value: "Pal Zileri" },
     { label: "Palm Angels", value: "Palm Angels" },
     { label: "Paloma Barceló", value: "Paloma Barceló" },
     { label: "Paltò", value: "Paltò" },
     { label: "PANGAIA", value: "PANGAIA" },
     { label: "Paolo Pecora", value: "Paolo Pecora" },
     { label: "Paoloni", value: "Paoloni" },
     { label: "Parajumpers", value: "Parajumpers" },
     { label: "Paris Texas", value: "Paris Texas" },
     { label: "Parts Of 4", value: "Parts Of 4" },
     { label: "Pas Normal Studios", value: "Pas Normal Studios" },
     { label: "Patagonia", value: "Patagonia" },
     { label: "Patou", value: "Patou" },
     { label: "Patrizia Pepe", value: "Patrizia Pepe" },
     { label: "Paul & Shark", value: "Paul & Shark" },
     { label: "Paul Smith", value: "Paul Smith" },
     { label: "People", value: "People" },
     { label: "People Of Shibuya", value: "People Of Shibuya" },
     { label: "Pepe Jeans", value: "Pepe Jeans" },
     { label: "Perfect Moment", value: "Perfect Moment" },
     { label: "PERSÉE", value: "PERSÉE" },
     { label: "Persol", value: "Persol" },
     { label: "Peserico", value: "Peserico" },
     { label: "Peter Do", value: "Peter Do" },
     { label: "Peuterey", value: "Peuterey" },
     { label: "Philipp Plein", value: "Philipp Plein" },
     { label: "Philippe Model", value: "Philippe Model" },
     { label: "Philosophy", value: "Philosophy" },
     { label: "Piazza Sempione", value: "Piazza Sempione" },
     { label: "Pieces", value: "Pieces" },
     { label: "Pierre Louis Mascia", value: "Pierre Louis Mascia" },
     { label: "Pinko", value: "Pinko" },
     { label: "Piquadro", value: "Piquadro" },
     { label: "Plan C", value: "Plan C" },
     { label: "Pleasures", value: "Pleasures" },
     { label: "Pollini", value: "Pollini" },
     { label: "Polo Ralph Lauren", value: "Polo Ralph Lauren" },
     { label: "Portolano", value: "Portolano" },
     { label: "Portuguese Flannel", value: "Portuguese Flannel" },
     { label: "Poupette", value: "Poupette" },
     { label: "Prada", value: "Prada" },
     { label: "Premiata", value: "Premiata" },
     { label: "Proenza Schouler", value: "Proenza Schouler" },
     { label: "PS by Paul Smith", value: "PS by Paul Smith" },
     { label: "PT Torino", value: "PT Torino" },
     { label: "PT01", value: "PT01" },
     { label: "PUMA", value: "PUMA" },
     { label: "Purple Brand", value: "Purple Brand" },
     { label: "Q", value: "Q" },
     { label: "Quay", value: "Quay" },
     { label: "R", value: "R" },
     { label: "R13", value: "R13" },
     { label: "Rachel Glauber", value: "Rachel Glauber" },
     { label: "Raey", value: "Raey" },
     { label: "Raf Simons", value: "Raf Simons" },
     { label: "Rag & Bone", value: "Rag & Bone" },
     { label: "Rails", value: "Rails" },
     { label: "Rains", value: "Rains" },
     { label: "Ralph Lauren", value: "Ralph Lauren" },
     { label: "Ralph Lauren Collecti", value: "Ralph Lauren Collecti" },
     { label: "Ralph Lauren Purple L", value: "Ralph Lauren Purple L" },
     { label: "Ramy Brook", value: "Ramy Brook" },
     { label: "Rassvet (PACCBET)", value: "Rassvet (PACCBET)" },
     { label: "Ray-Ban", value: "Ray-Ban" },
     { label: "Re-hash", value: "Re-hash" },
     { label: "RE/DONE", value: "RE/DONE" },
     { label: "Rebecca Taylor", value: "Rebecca Taylor" },
     { label: "Rebecca Vallance", value: "Rebecca Vallance" },
     { label: "Rebel Queen By Liu Jo", value: "Rebel Queen By Liu Jo" },
     { label: "RED Valentino", value: "RED Valentino" },
     { label: "Red(v)", value: "Red(v)" },
     { label: "Reebok", value: "Reebok" },
     { label: "Reebok X Victoria Bec", value: "Reebok X Victoria Bec" },
     { label: "Reformation", value: "Reformation" },
     { label: "Reina Olga", value: "Reina Olga" },
     { label: "Rejina Pyo", value: "Rejina Pyo" },
     { label: "Relish", value: "Relish" },
     { label: "REMAIN Birger Christe", value: "REMAIN Birger Christe" },
     { label: "Rene Caovilla", value: "Rene Caovilla" },
     { label: "Replay", value: "Replay" },
     { label: "Represent", value: "Represent" },
     { label: "retroféte", value: "retroféte" },
     { label: "Retrosuperfuture", value: "Retrosuperfuture" },
     { label: "Rhude", value: "Rhude" },
     { label: "Rick Owens", value: "Rick Owens" },
     { label: "Rick Owens DRKSHDW", value: "Rick Owens DRKSHDW" },
     { label: "Rina Limor", value: "Rina Limor" },
     { label: "River Island", value: "River Island" },
     { label: "Rivka Friedman", value: "Rivka Friedman" },
     { label: "RIXO London", value: "RIXO London" },
     { label: "Robert Clergerie", value: "Robert Clergerie" },
     { label: "Robert Graham", value: "Robert Graham" },
     { label: "Roberto Cavalli", value: "Roberto Cavalli" },
     { label: "Roberto Collina", value: "Roberto Collina" },
     { label: "Rochas", value: "Rochas" },
     { label: "Rodebjer", value: "Rodebjer" },
     { label: "Roger Vivier", value: "Roger Vivier" },
     { label: "ROKH", value: "ROKH" },
     { label: "Rosemunde", value: "Rosemunde" },
     { label: "Rosetta Getty", value: "Rosetta Getty" },
     { label: "Rossignol", value: "Rossignol" },
     { label: "ROTATE BIRGER CHRISTE", value: "ROTATE BIRGER CHRISTE" },
     { label: "Roy Rogers", value: "Roy Rogers" },
     { label: "Rrd", value: "Rrd" },
     { label: "RRL", value: "RRL" },
     { label: "RTA", value: "RTA" },
     { label: "Ruslan Baginskiy", value: "Ruslan Baginskiy" },
     { label: "S", value: "S" },
     { label: "Saachi", value: "Saachi" },
     { label: "Sabrina Designs", value: "Sabrina Designs" },
     { label: "Sacai", value: "Sacai" },
     { label: "Sachin & Babi", value: "Sachin & Babi" },
     { label: "Saint Laurent", value: "Saint Laurent" },
     { label: "Saks Fifth Avenue", value: "Saks Fifth Avenue" },
     { label: "Salomon", value: "Salomon" },
     { label: "Salvatore Santoro", value: "Salvatore Santoro" },
     { label: "Sam Edelman", value: "Sam Edelman" },
     { label: "Samantha Sung", value: "Samantha Sung" },
     { label: "Sams e & Sams e", value: "Sams e & Sams e" },
     { label: "Samsøe & Samsøe", value: "Samsøe & Samsøe" },
     { label: "Samuel B.", value: "Samuel B." },
     { label: "Sandro", value: "Sandro" },
     { label: "Santoni", value: "Santoni" },
     { label: "Sarah Chofakian", value: "Sarah Chofakian" },
     { label: "Saucony", value: "Saucony" },
     { label: "Save The Duck", value: "Save The Duck" },
     { label: "SCAROSSO", value: "SCAROSSO" },
     { label: "Schutz", value: "Schutz" },
     { label: "Scotch & Soda", value: "Scotch & Soda" },
     { label: "SCOTT & SCOTT LONDON", value: "SCOTT & SCOTT LONDON" },
     { label: "Sea", value: "Sea" },
     { label: "Seafolly", value: "Seafolly" },
     { label: "Second Female", value: "Second Female" },
     { label: "See By Chloé", value: "See By Chloé" },
     { label: "SELECTED", value: "SELECTED" },
     { label: "Self-Portrait", value: "Self-Portrait" },
     { label: "Semicouture", value: "Semicouture" },
     { label: "Sergio Rossi", value: "Sergio Rossi" },
     { label: "Shashi", value: "Shashi" },
     { label: "Shaun Leane", value: "Shaun Leane" },
     { label: "SHAY", value: "SHAY" },
     { label: "Shirtaporter", value: "Shirtaporter" },
     { label: "Silvian Heach", value: "Silvian Heach" },
     { label: "Simon Miller", value: "Simon Miller" },
     { label: "Simone Rocha", value: "Simone Rocha" },
     { label: "Sir. The Label", value: "Sir. The Label" },
     { label: "Siviglia", value: "Siviglia" },
     { label: "Skechers", value: "Skechers" },
     { label: "Skims", value: "Skims" },
     { label: "Skin", value: "Skin" },
     { label: "Sleeper", value: "Sleeper" },
     { label: "SLVRLAKE Denim", value: "SLVRLAKE Denim" },
     { label: "Snow Peak", value: "Snow Peak" },
     { label: "SO & CO", value: "SO & CO" },
     { label: "Soallure", value: "Soallure" },
     { label: "Solid & Striped", value: "Solid & Striped" },
     { label: "Sophia Webster", value: "Sophia Webster" },
     { label: "Sophie Bille Brahe", value: "Sophie Bille Brahe" },
     { label: "Soulland", value: "Soulland" },
     { label: "Souvenir Clubbing", value: "Souvenir Clubbing" },
     { label: "Spanx", value: "Spanx" },
     { label: "Spinelli Kilcollin", value: "Spinelli Kilcollin" },
     { label: "Splendid", value: "Splendid" },
     { label: "Sportmax", value: "Sportmax" },
     { label: "Sporty & Rich", value: "Sporty & Rich" },
     { label: "St. John", value: "St. John" },
     { label: "Stand Studio", value: "Stand Studio" },
     { label: "STAUD", value: "STAUD" },
     { label: "Stella McCartney", value: "Stella McCartney" },
     { label: "Stella Nova", value: "Stella Nova" },
     { label: "Sterling Forever", value: "Sterling Forever" },
     { label: "Steve Madden", value: "Steve Madden" },
     { label: "Stine Goya", value: "Stine Goya" },
     { label: "Stone Island", value: "Stone Island" },
     { label: "Stone Island Shadow P", value: "Stone Island Shadow P" },
     { label: "Stuart Weitzman", value: "Stuart Weitzman" },
     { label: "Studio Nicholson", value: "Studio Nicholson" },
     { label: "Stuhrling Original", value: "Stuhrling Original" },
     { label: "Stussy", value: "Stussy" },
     { label: "Suicoke", value: "Suicoke" },
     { label: "Sun 68", value: "Sun 68" },
     { label: "Sunnei", value: "Sunnei" },
     { label: "Sunspel", value: "Sunspel" },
     { label: "Suoli", value: "Suoli" },
     { label: "superdown", value: "superdown" },
     { label: "Superga", value: "Superga" },
     { label: "Supreme", value: "Supreme" },
     { label: "Suzanne Kalan", value: "Suzanne Kalan" },
     { label: "Suzy Levian", value: "Suzy Levian" },
     { label: "Swarovski", value: "Swarovski" },
     { label: "Sydney Evan", value: "Sydney Evan" },
     { label: "T", value: "T" },
     { label: "T By Alexander Wang", value: "T By Alexander Wang" },
     { label: "Tagliatore", value: "Tagliatore" },
     { label: "Takeshy Kurosawa", value: "Takeshy Kurosawa" },
     { label: "Talbots", value: "Talbots" },
     { label: "Tasaki", value: "Tasaki" },
     { label: "Tateossian", value: "Tateossian" },
     { label: "Taylor", value: "Taylor" },
     { label: "Ted Baker", value: "Ted Baker" },
     { label: "Tekla", value: "Tekla" },
     { label: "Tela", value: "Tela" },
     { label: "The Alkemistry", value: "The Alkemistry" },
     { label: "The Attico", value: "The Attico" },
     { label: "The Elder Statesman", value: "The Elder Statesman" },
     { label: "The Gigi", value: "The Gigi" },
     { label: "The Kooples", value: "The Kooples" },
     { label: "The North Face", value: "The North Face" },
     { label: "The Range", value: "The Range" },
     { label: "The Row", value: "The Row" },
     { label: "The Upside", value: "The Upside" },
     { label: "THEMOIRÈ", value: "THEMOIRÈ" },
     { label: "Theory", value: "Theory" },
     { label: "Thom Browne", value: "Thom Browne" },
     { label: "Tibi", value: "Tibi" },
     { label: "Timberland", value: "Timberland" },
    //  { label: "Tintoria Mattei 954", value: "Tintoria Mattei 954" },
     { label: "Tod's", value: "Tod's" },
     { label: "Todd Snyder", value: "Todd Snyder" },
     { label: "Tom Ford", value: "Tom Ford" },
     { label: "Tom Wood", value: "Tom Wood" },
    //  { label: "Tommy Hilfiger", value: "Tommy Hilfiger" },
     { label: "Tonello", value: "Tonello" },
     { label: "TOPMAN", value: "TOPMAN" },
     { label: "TOPSHOP", value: "TOPSHOP" },
     { label: "Tory Burch", value: "Tory Burch" },
     { label: "Tory Sport", value: "Tory Sport" },
     { label: "Tosca Blu", value: "Tosca Blu" },
     { label: "Totême", value: "Totême" },
     { label: "Trina Turk", value: "Trina Turk" },
    //  { label: "True Religion", value: "True Religion" },
     { label: "True Rocks", value: "True Rocks" },
     { label: "True Royal", value: "True Royal" },
     { label: "Trussardi", value: "Trussardi" },
     { label: "Tularosa", value: "Tularosa" },
     { label: "Twin Set", value: "Twin Set" },
     { label: "Twinset", value: "Twinset" },
     { label: "U", value: "U" },
     { label: "UGG", value: "UGG" },
     { label: "Ulla Johnson", value: "Ulla Johnson" },
     { label: "Uma Wang", value: "Uma Wang" },
     { label: "Undercover", value: "Undercover" },
     { label: "Universal Works", value: "Universal Works" },
     { label: "V", value: "V" },
     { label: "Valentino", value: "Valentino" },
     { label: "Vanessa Bruno", value: "Vanessa Bruno" },
     { label: "Vans", value: "Vans" },
     { label: "Varley", value: "Varley" },
     { label: "Veja", value: "Veja" },
     { label: "Velvet", value: "Velvet" },
     { label: "Vero Moda", value: "Vero Moda" },
     { label: "Veronica Beard", value: "Veronica Beard" },
     { label: "Versace", value: "Versace" },
     { label: "Versace Eyewear", value: "Versace Eyewear" },
     { label: "Versace Jeans Couture", value: "Versace Jeans Couture" },
     { label: "Versus", value: "Versus" },
     { label: "Vetements", value: "Vetements" },
     { label: "Vic Matié", value: "Vic Matié" },
     { label: "ViCOLO", value: "ViCOLO" },
     { label: "Victoria Beckham", value: "Victoria Beckham" },
     { label: "Vila", value: "Vila" },
     { label: "Vilebrequin", value: "Vilebrequin" },
     { label: "Vince", value: "Vince" },
     { label: "Vince Camuto", value: "Vince Camuto" },
     { label: "Vintouch Italy", value: "Vintouch Italy" },
     { label: "Vision Of Super", value: "Vision Of Super" },
     { label: "Visvim", value: "Visvim" },
     { label: "Vivetta", value: "Vivetta" },
     { label: "Vivienne Westwood", value: "Vivienne Westwood" },
     { label: "ViX", value: "ViX" },
     { label: "VTMNTS", value: "VTMNTS" },
     { label: "W", value: "W" },
     { label: "Wales Bonner", value: "Wales Bonner" },
     { label: "Walter Baker", value: "Walter Baker" },
     { label: "Wandler", value: "Wandler" },
     { label: "Wardrobe NYC", value: "Wardrobe NYC" },
     { label: "we11done", value: "we11done" },
     { label: "Weekend by Maxmara", value: "Weekend by Maxmara" },
     { label: "WEILI ZHENG", value: "WEILI ZHENG" },
     { label: "WeWoreWhat", value: "WeWoreWhat" },
     { label: "Whistles", value: "Whistles" },
     { label: "White Sand", value: "White Sand" },
     { label: "Wolford", value: "Wolford" },
     { label: "WOOD WOOD", value: "WOOD WOOD" },
     { label: "Woolrich", value: "Woolrich" },
     { label: "WOOYOUNGMI", value: "WOOYOUNGMI" },
     { label: "Wrangler", value: "Wrangler" },
     { label: "X", value: "X" },
     { label: "Xacus", value: "Xacus" },
     { label: "Xirena", value: "Xirena" },
     { label: "Y", value: "Y" },
     { label: "Y's Yohji Yamamoto", value: "Y's Yohji Yamamoto" },
     { label: "Y-3", value: "Y-3" },
     { label: "Y. Project", value: "Y. Project" },
     { label: "YMC", value: "YMC" },
     { label: "Yohji Yamamoto", value: "Yohji Yamamoto" },
     { label: "Yuzefi", value: "Yuzefi" },
     { label: "Yves Salomon", value: "Yves Salomon" },
     { label: "Yvonne Léon", value: "Yvonne Léon" },
     { label: "Z", value: "Z" },
     { label: "Z Zegna", value: "Z Zegna" },
     { label: "Zadig & Voltaire", value: "Zadig & Voltaire" },
     { label: "Zanellato", value: "Zanellato" },
     { label: "Zanone", value: "Zanone" },
     { label: "Zimmermann", value: "Zimmermann" },
     { label: "0-9", value: "0-9" },
     { label: "032c", value: "032c" },
     { label: "1017 ALYX 9SM", value: "1017 ALYX 9SM" },
     { label: "12 STOREEZ", value: "12 STOREEZ" },
     { label: "16Arlington", value: "16Arlington" },
     { label: "3 MONCLER GRENOBLE", value: "3 MONCLER GRENOBLE" },
     { label: "3.1 Phillip Lim", value: "3.1 Phillip Lim" },
     { label: "3x1", value: "3x1" },
     { label: "40weft", value: "40weft" },
     { label: "424", value: "424" },
     { label: "7 For All Mankind", value: "7 For All Mankind" },
     { label: "8 by YOOX", value: "8 by YOOX" },
     { label: "8pm", value: "8pm" },
];
