export const material = [
     { label: "Canvas", value: "Canvas" },
     { label: "Cashmere", value: "Cashmere" },
     { label: "Chiffon", value: "Chiffon" },
     { label: "Corduroy", value: "Corduroy" },
     { label: "Cotton", value: "Cotton" },
     { label: "Denim", value: "Denim" },
     { label: "Flannel", value: "Flannel" },
     { label: "Fleece", value: "Fleece" },
     { label: "Fur", value: "Fur" },
     { label: "Goose", value: "Goose" },
     { label: "Lace", value: "Lace" },
     { label: "Leather", value: "Leather" },
     { label: "Linen", value: "Linen" },
     { label: "Metal", value: "Metal" },
     { label: "Neoprene", value: "Neoprene" },
     { label: "Satin", value: "Satin" },
     { label: "Silk", value: "Silk" },
     { label: "Suede", value: "Suede" },
     { label: "Synthetic", value: "Synthetic" },
     { label: "Tulle", value: "Tulle" },
     { label: "Tweed", value: "Tweed" },
     { label: "Velvet", value: "Velvet" },
     { label: "Wool", value: "Wool" },
];
