export const stores = [
     { label: "Alexander McQueen", value: "Alexander McQueen" },
     { label: "Alexander Wang", value: "Alexander Wang" },
     { label: "AllSaints", value: "AllSaints" },
     { label: "AllSole", value: "AllSole" },
     { label: "Ami Paris", value: "Ami Paris" },
     { label: "Ann Taylor", value: "Ann Taylor" },
     { label: "Annoushka Ltd.", value: "Annoushka Ltd." },
     { label: "Aspinal of London", value: "Aspinal of London" },
     { label: "Atterley", value: "Atterley" },
     { label: "Bebe", value: "Bebe" },
     { label: "Black Halo", value: "Black Halo" },
     { label: "Black.co.uk", value: "Black.co.uk" },
     { label: "Blue & Cream", value: "Blue & Cream" },
     { label: "Bogner", value: "Bogner" },
     { label: "Bottega Veneta", value: "Bottega Veneta" },
     { label: "Brother2Brother", value: "Brother2Brother" },
     { label: "Brown Bag", value: "Brown Bag" },
     { label: "Browns Fashion", value: "Browns Fashion" },
     { label: "Casadei", value: "Casadei" },
     { label: "Cettire", value: "Cettire" },
     { label: "Charles Clinkard", value: "Charles Clinkard" },
     { label: "Coggles", value: "Coggles" },
     { label: "Coltorti", value: "Coltorti" },
     { label: "Cosabella", value: "Cosabella" },
     { label: "Country House Outdoor", value: "Country House Outdoor" },
     {
          label: "Couverture & The Garbstore",
          value: "Couverture & The Garbstore",
     },
     { label: "Daniel Footwear", value: "Daniel Footwear" },
     { label: "Dolce & Gabbana", value: "Dolce & Gabbana" },
     { label: "DYLANLEX", value: "DYLANLEX" },
     { label: "Eleonora Bonucci", value: "Eleonora Bonucci" },
     { label: "END.", value: "END." },
     { label: "Eraldo", value: "Eraldo" },
     { label: "Esquire Clothing", value: "Esquire Clothing" },
     { label: "Faherty Brand", value: "Faherty Brand" },
     { label: "FARFETCH", value: "FARFETCH" },
     { label: "Fleur du Mal", value: "Fleur du Mal" },
     { label: "FRAME", value: "FRAME" },
     { label: "Free People", value: "Free People" },
     { label: "FRMODA", value: "FRMODA" },
     { label: "FWRD", value: "FWRD" },
     { label: "GIGLIO.COM", value: "GIGLIO.COM" },
     { label: "Gilt", value: "Gilt" },
     { label: "Giuseppe Zanotti", value: "Giuseppe Zanotti" },
     { label: "GRIFO210", value: "GRIFO210" },
     { label: "H&M", value: "H&M" },
     { label: "Hampden", value: "Hampden" },
     { label: "Harrods", value: "Harrods" },
     { label: "Hervia", value: "Hervia" },
     { label: "HIP", value: "HIP" },
     { label: "Hobbs", value: "Hobbs" },
     { label: "HUGO BOSS", value: "HUGO BOSS" },
     { label: "HUNTER", value: "HUNTER" },
     { label: "Jarlo", value: "Jarlo" },
     { label: "Jenny Bird", value: "Jenny Bird" },
     { label: "Jimmy Choo", value: "Jimmy Choo" },
     { label: "John Varvatos", value: "John Varvatos" },
     { label: "Jomashop", value: "Jomashop" },
     { label: "JOSEPH", value: "JOSEPH" },
     { label: "Jules B", value: "Jules B" },
     { label: "Kurt Geiger", value: "Kurt Geiger" },
     { label: "La Garçonne", value: "La Garçonne" },
     { label: "Lane Crawford", value: "Lane Crawford" },
     { label: "Leam", value: "Leam" },
     { label: "Liberty London", value: "Liberty London" },
     { label: "LN-CC", value: "LN-CC" },
     { label: "Loeffler Randall", value: "Loeffler Randall" },
     { label: "Luciana Bari", value: "Luciana Bari" },
     { label: "LUISA VIA ROMA", value: "LUISA VIA ROMA" },
     { label: "Lulu Guinness", value: "Lulu Guinness" },
     { label: "Mackage", value: "Mackage" },
     { label: "Mackintosh", value: "Mackintosh" },
     { label: "Madewell", value: "Madewell" },
     { label: "MATCHESFASHION", value: "MATCHESFASHION" },
     { label: "MCLabels", value: "MCLabels" },
     { label: "Michele Franzese Moda", value: "Michele Franzese Moda" },
     { label: "Moda Operandi", value: "Moda Operandi" },
     { label: "Modes", value: "Modes" },
     { label: "Moss", value: "Moss" },
     { label: "Mother", value: "Mother" },
     { label: "MR PORTER", value: "MR PORTER" },
     { label: "Mulberry", value: "Mulberry" },
     { label: "MyBag", value: "MyBag" },
     { label: "Mytheresa", value: "Mytheresa" },
     { label: "MZ Wallace", value: "MZ Wallace" },
     { label: "NET-A-PORTER", value: "NET-A-PORTER" },
     { label: "Nili Lotan", value: "Nili Lotan" },
     { label: "Orlebar Brown", value: "Orlebar Brown" },
     { label: "Quay", value: "Quay" },
     { label: "Rachel Pally", value: "Rachel Pally" },
     { label: "Reformation", value: "Reformation" },
     { label: "REVOLVE", value: "REVOLVE" },
     { label: "River Island", value: "River Island" },
     { label: "Rue La La", value: "Rue La La" },
     { label: "Sachin & Babi", value: "Sachin & Babi" },
     { label: "Saks OFF 5TH", value: "Saks OFF 5TH" },
     { label: "SANTA EULALIA", value: "SANTA EULALIA" },
     { label: "scotts", value: "scotts" },
     { label: "Selfridges", value: "Selfridges" },
     { label: "Senreve", value: "Senreve" },
     { label: "SEVENSTORE", value: "SEVENSTORE" },
     { label: "Shopbop", value: "Shopbop" },
     { label: "SSENSE", value: "SSENSE" },
     { label: "Standout", value: "Standout" },
     { label: "Stella McCartney", value: "Stella McCartney" },
     { label: "Suit Negozi", value: "Suit Negozi" },
     { label: "Talbots", value: "Talbots" },
     { label: "TESSABIT", value: "TESSABIT" },
     { label: "Tessuti UK", value: "Tessuti UK" },
     { label: "THAHAB", value: "THAHAB" },
     { label: "The Hut", value: "The Hut" },
     { label: "THE OUTNET.COM", value: "THE OUTNET.COM" },
     { label: "Todd Snyder", value: "Todd Snyder" },
     { label: "Tory Burch", value: "Tory Burch" },
     { label: "Triads", value: "Triads" },
     { label: "Veronica Beard", value: "Veronica Beard" },
     { label: "Vince", value: "Vince" },
     { label: "VITKAC", value: "VITKAC" },
     { label: "Whistles", value: "Whistles" },
     { label: "Wolf & Badger", value: "Wolf & Badger" },
     { label: "Woodhouse Clothing", value: "Woodhouse Clothing" },
     { label: "YOOX", value: "YOOX" },
     { label: "3.1 Phillip Lim", value: "3.1 Phillip Lim" },
     { label: "7 for all mankind", value: "7 for all mankind" },
     { label: "& Other Stories", value: "& Other Stories" },
];
